### PR TITLE
Initial dark mode implementation

### PR DESCRIPTION
**Pull request by laofuLF**
the initial solution for issue #41. 

Added [less variable](https://ant.design/docs/react/customize-theme) override for dark mode. 
Some code cleaning for arbitrary color/background-color settings. 
Tested on home page, sidebar, and most admin table components. 

TODO: set up all other components and fix inappropriate color override of each component for light/dark mode.

### CODE REVIEW

**Comment by bcpierce00** [comment]
Is this PR working?  I get 
image

**Comment by laofuLF** [comment]
styled-components is a module that needs to be installed. Try `npm install styled-components`

**Comment by bcpierce00** [comment]
Thanks -- that's better!

**Comment by bcpierce00** [comment]
It does seem to basically work for me (though the middle pane seems to be getting cut off on the left a bit).  I notice that there is also one conflicting file at the moment -- we should merge the current master into the PR.

**Comment by laofuLF** [comment]
Thanks for letting me know. The conflicting file has been solved manually. I deleted lines of code that are no longer used in the master branch and updated this PR. There should be no conflict to merge now. I think it's better to open an issue about any color that looks off when switching mode with screenshots, so that @dlwangyilin and I can look into them. Thank you!

**Pull request closed without merging**
