### PR TITLE
Sort text chat and video chat alphabetically

### PR DESCRIPTION
**Pull request by bingfeizh**
As I do not have access to some channel data including Paper Channels and maybe others, please test it and leave bugs here. Thanks.

### CODE REVIEW

**Comment by bcpierce00** [comment]
Looks like some code might be duplicated some of the sorting functions?  Otherwise, seems to work for me.

**Comment by bingfeizh** [comment]
> Looks like some code might be duplicated some of the sorting functions? Otherwise, seems to work for me.

Great! It is interesting that if I put the duplicated code into a function it does not work. I'm working on it now. Just want to make sure this approach works for all the channels.

**Comment by bcpierce00** [comment]
I think there are some other things in the UI that are not sorted correctly.  E.g., the list of "upcoming sessions" on the Live Sessions page, and the list of upcoming events in each room.  Note that there are two bugs in the following image: the three top-level sessions are not sorted by name, and the individual items on the HIW list (for example) also not.

Would be great to fix these too!!

image

**Comment by bingfeizh** [comment]
> I think there are some other things in the UI that are not sorted correctly. E.g., the list of "upcoming sessions" on the Live Sessions page, and the list of upcoming events in each room. Note that there are two bugs in the following image: the three top-level sessions are not sorted by name, and the individual items on the HIW list (for example) also not.
> 
> Would be great to fix these too!!
> 
> image

OK I'll try.

**Pull request closed without merging**
