### PR TITLE
Change ./Chat to TypeScript

### PR DESCRIPTION
**Pull request by bingfeizh**

### CODE REVIEW

**Comment by jon-bell** [comment]
I would like to ask that this not be merged in, and that you stop working on typescriptifying the chat until I am done refactoring it. Some of this will end up deleted, so it is maybe not that worthwhile to focus on it right now.

**Comment by bingfeizh** [comment]
> I would like to ask that this not be merged in, and that you stop working on typescriptifying the chat until I am done refactoring it. Some of this will end up deleted, so it is maybe not that worthwhile to focus on it right now.

Sure. I'll redo until you finish this part. BTW is that safe working on SignIn, SignUp and SignOut?

**Comment by jon-bell** [comment]
I am working on: Program, sidebar, chat

**Comment by bingfeizh** [comment]
> I am working on: Program, sidebar, chat

Thanks!

**Pull request closed without merging**
